### PR TITLE
First round of review

### PR DESCRIPTION
**Pull request by tschaume**
TODO's are added as comments. I think "signac database" is currently only vaguely explained. It would be instructive and very informative to address its functionality and implementation in more detail.

### CODE REVIEW

**Comment by vyasr** [comment]
@tschaume Thanks so much for the feedback! The attention to detail is highly appreciated. I agree, we can be a little more detailed about how the database works. I'll address the rest of your comments and TODOs ASAP and then merge.

**Comment by vyasr** [comment]
I'm currently going through your fork and addressing your TODO items. One concrete change that might interest you: it turns out that since writing this, we have found that it is in fact possible (and not terribly difficult) to integrate signac with Sacred. As a result, I am modifying that part of the text.

**Comment by tschaume** [comment]
That's great news! Looking forward to the new version of that part of the text. Reading the old version, I had a hunch it should be possible somehow but I don't know signac or Sacred infrastructure enough to know for sure.

**Comment by vyasr** [comment]
@tschaume sorry for the long delay with this, I'm currently traveling and juggling a few other papers as well. I've merged in your PR, and I've made changes to address your TODOs. They're currently sitting in a branch on my repo that I've invited you to as a collaborator. If you accept that, I can add you as a reviewer for that pull request so that you can see if I've addressed your points satisfactorily.

Ideally I'd like to merge this in sometime Friday just in case another reviewer starts looking through it, but if you would like more time let me know and I can leave the pull request open until next week! Of course, you can also review after I have merged but I assume that it will be easier for you to see how I've addressed each of your specific points with the diff. Let me know your schedule when you get a chance. Thanks!

**Pull request merged**
